### ISSUE TITLE
Make  edit fields pre filled

### ISSUE THREAD

**Issue by LiibaanHalane** [DariaBatiuk/NB-Project-Tracker#48]

**Comment by Ryguy506** [comment]
done in ui pull request

**Comment by LiibaanHalane** [comment]
The text remains after typing, but it is not prefilled with the info already present, I think

**Comment by LiibaanHalane** [comment]
It may also have to do with the id/class names having changed, I'm unsure, I suppose daria wasn't able to fix the merge conflicts so I'm pushing some of your code with mine
